# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  imhex = {
    pname = "imhex";
    version = "v1.29.0";
    src = fetchFromGitHub ({
      owner = "WerWolv";
      repo = "imhex";
      rev = "v1.29.0";
      fetchSubmodules = true;
      sha256 = "sha256-dghyv7rpqGs5dt51ziAaeb/Ba7rGEcJ54AYKRJ2xXuk=";
    });
  };
}
