[imhex]
src.github = "WerWolv/imhex"
fetch.github = "WerWolv/imhex"
git.fetchSubmodules = true

[imhex-patterns]
src.github = "WerWolv/ImHex-Patterns"
fetch.github = "WerWolv/ImHex-Patterns"

[gh-poi]
src.github = "seachicken/gh-poi"
fetch.github = "seachicken/gh-poi"
passthru = {vendorSha256 = "sha256-D/YZLwwGJWCekq9mpfCECzJyJ/xSlg7fC6leJh+e8i0="}

[commitizen]
src.github = "commitizen-tools/commitizen"
fetch.github = "commitizen-tools/commitizen"

[vscord]
src.vsmarketplace = "LeonardSSH.vscord"
fetch.vsmarketplace = "LeonardSSH.vscord"

[vscode-zig]
src.vsmarketplace = "ziglang.vscode-zig"
fetch.vsmarketplace = "ziglang.vscode-zig"

[andromeda]
src.vsmarketplace = "EliverLara.andromeda"
fetch.vsmarketplace = "EliverLara.andromeda"

[mrpack-install]
src.github = "nothub/mrpack-install"
fetch.github = "nothub/mrpack-install"
passthru = {vendorHash = "sha256-ZWaWwsAqAcewCyAzDjp9rBBJTl4RsCsA4efBDEcGVss="}
