[imhex]
src.github = "WerWolv/imhex"
fetch.github = "WerWolv/imhex"
git.fetchSubmodules = true

[imhex-patterns]
src.github = "WerWolv/ImHex-Patterns"
fetch.github = "WerWolv/ImHex-Patterns"

[imhex-git]
src.git = "https://github.com/WerWolv/ImHex"
src.branch = "master"
fetch.github = "WerWolv/imhex"
git.fetchSubmodules = true

[imhex-patterns-git]
src.git = "https://github.com/WerWolv/ImHex-Patterns"
src.branch = "master"
fetch.github = "WerWolv/ImHex-Patterns"

[gh-poi]
src.github = "seachicken/gh-poi"
fetch.github = "seachicken/gh-poi"
passthru = {vendorHash = "sha256-D/YZLwwGJWCekq9mpfCECzJyJ/xSlg7fC6leJh+e8i0="}

[vscord]
src.vsmarketplace = "LeonardSSH.vscord"
fetch.vsmarketplace = "LeonardSSH.vscord"

[vscode-zig]
src.vsmarketplace = "ziglang.vscode-zig"
fetch.vsmarketplace = "ziglang.vscode-zig"

[andromeda]
src.vsmarketplace = "EliverLara.andromeda"
fetch.vsmarketplace = "EliverLara.andromeda"

[mrpack-install]
src.github = "nothub/mrpack-install"
fetch.github = "nothub/mrpack-install"
passthru = {vendorHash = "sha256-az+NpP/hCIq2IfO8Bmn/qG3JVypeDljJ0jWg6yT6hks="}

[vscode-coconut]
src.vsmarketplace = "evhub.coconut"
fetch.vsmarketplace = "evhub.coconut"

[monokai-highcontrast]
src.vsmarketplace = "DataByne.theme-monokai-hc"
fetch.vsmarketplace = "DataByne.theme-monokai-hc"

[vscode-lark]
src.vsmarketplace = "dirk-thomas.vscode-lark"
fetch.vsmarketplace = "dirk-thomas.vscode-lark"

[github-code-owners]
src.vsmarketplace = "chdsbd.github-code-owners"
fetch.vsmarketplace = "chdsbd.github-code-owners"
