name: "ci"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  check_flake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: check flake
      run: nix flake check

  generate_matrix:
    needs: ["check_flake"]
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.generate_packages.outputs.packages }}
    steps:
      - uses: actions/checkout@v6
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: generate flake.json
        run: nix flake show --json > flake.json
      - name: artifact flake.json
        uses: actions/upload-artifact@v7
        with:
          name: flake.json
          path: flake.json
      - id: generate_packages
        run: |
          packages=$(jq -c '.inventory.packages.output.children."x86_64-linux".children | keys' < flake.json)
          printf "packages=%s" "$packages" >> $GITHUB_OUTPUT

  build:
    needs: [generate_matrix]
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.generate_matrix.outputs.packages)}}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - uses: cachix/cachix-action@v17
      with:
        name: starrfox
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build --print-build-logs .#${{ matrix.package }}
