name: "check flake"

on:
    push:
        branches: [main]
  
jobs:
    check:
        name: Check
        runs-on: ubuntu-22.04
        steps:
        - uses: actions/checkout@v4
        - name: Install Nix
          uses: DeterminateSystems/nix-installer-action@main
        - name: check flake
          run: nix flake check
