name: "update daily"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
    contents: write
    pull-requests: write

jobs:
    update:
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v4
            - name: Install Nix
              uses: DeterminateSystems/nix-installer-action@main
            - uses: cachix/cachix-action@v15
              with:
                name: starrfox
                authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
            - run: nix develop --command just update-git-packages
            - name: Create PR
              id: createpr
              uses: peter-evans/create-pull-request@v7
              with:
                title: "update daily packages"
                branch: update
                branch-suffix: timestamp
                delete-branch: true
                commit-message: "update daily packages"
                token: ${{ secrets.CUCK_GITHUB }}
                labels: |
                  automated
                  packages/update
            - name: enable auto-merge
              if: steps.createpr.outputs.pull-request-operation == 'created'
              run: gh pr merge --auto --squash ${{ steps.createpr.outputs.pull-request-number }}
              env:
                GH_TOKEN: ${{ secrets.CUCK_GITHUB }}
