name: "update biweekly"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1,15 * *"

permissions:
    contents: write
    pull-requests: write

jobs:
    update:
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v4
            - name: Install Nix
              uses: DeterminateSystems/nix-installer-action@main
            - uses: cachix/cachix-action@v13
              with:
                name: starrfox
                authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
            - run: nix flake update
            - run: nix develop --command just update-packages
            - name: Create PR
              uses: peter-evans/create-pull-request@v5
              with:
                title: "update packages and lock"
                branch: update
                branch-suffix: timestamp
                delete-branch: true
                reviewers: StarrFox
                commit-message: "update packages and lock"
