name: "update"

on:
    workflow_dispatch:
    schedule:
      - cron: "0 4 1 * *"

jobs:
    update:
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v3
            - name: Install nix
              uses: DeterminateSystems/nix-installer-action@main
            - run: nix develop --command just update
            - name: Create PR
              uses: peter-evans/create-pull-request@v5
              with:
                title: "update packages and lock"
                branch: update
                branch-suffix: timestamp
                delete-branch: true
                reviewers: StarrFox
